name: PrePro Collaborative
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title/
filters: [Text, Image, Model, Interactive, Other]
collections:
    cite:
        output: true
        permalink: /projects/:path/
    projects:
        output: true
        permalink: /projects/:title/
